---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
data:
  enable-ocsp: "true"
  hsts-max-age: "63072000"
  hsts-preload: "true"
  http-snippet: |
    sendfile on;
  server-tokens: "false"
  ssl-session-tickets: "false"
