---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moto-ttt
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: moto-ttt
  local:
    path: /home/barrelmaker/moto-ttt-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ares
