---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: motofactorio4
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: motofactorio4
  local:
    path: /home/barrelmaker/gamedata/factorio/motofactorio4-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ares
