---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: primordial
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: primordial
  local:
    path: /home/barrelmaker/gamedata/minecraft/primordial-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ares
