---
- hosts: hermes
  tasks:
    - name: Create User Namespace
      k8s:
        state: present
        definition: "{{ lookup('template', './definitions/namespace-user.yaml') | from_yaml }}"

    - name: Create User Role Binding
      k8s:
        state: present
        definition: "{{ lookup('template', './definitions/rolebinding-user.yaml') | from_yaml }}"

    - name: Create User Resource Quota
      k8s:
        state: present
        definition: "{{ lookup('template', './definitions/resourcequota-user.yaml') | from_yaml }}"

    - name: Create User Limit Range
      k8s:
        state: present
        definition: "{{ lookup('template', './definitions/limitrange-user.yaml') | from_yaml }}"
